server:
  port: 0

spring:
  cloud:
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    region:
      static: eu-central-1
    sqs:
      endpoint: http://localhost:4566
      queue-url: http://localhost:4566/000000000000/songfile-queue
  security:
    oauth2:
      client:
        registration:
          spotify:
            authorization-grant-type: client_credentials
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka