server:
  port: 0

spring:
  cloud:
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    region:
      static: eu-central-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka