server:
  port: 0

spring:
  cloud:
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    region:
      static: eu-central-1
    sqs:
      endpoint: http://localhost:4566
  security:
    oauth2:
      client:
        registration:
          spotify:
            authorization-grant-type: client_credentials
            client-id: ${SPOTIFY_CLIENT_ID:498867fb3c40444da061af8033c4044b}
            client-secret: ${SPOTIFY_CLIENT_SECRET:f15cd44fe260488da6140620479b7090}
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka