server:
  port: 0

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/innowise-microservices-file-api
    password: BebraBebra
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    generate-ddl: true
  cloud:
    aws:
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
        region: ${AWS_REGION:eu-central-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:ANUJDEKAVADIYAEXAMPLE}
        secret-key: ${AWS_SECRET_ACCESS_KEY:2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY}
      region:
        static: ${AWS_REGION:eu-central-1}
      sqs:
        endpoint: ${AWS_ENDPOINT_URI:http://localhost:4566}
        queue-url: http://localhost:4566/000000000000/songfile-queue
      endpoint: ${AWS_ENDPOINT_URI:http://localhost:4566}

storage:
  local:
    path: /storage
  s3:
    bucket-name: songfile

logging:
  level:
    root=INFO:

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DISCOVERY_URI:http://localhost:8761/eureka}