server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://localhost:3306/innowise-microservices-file-api
    password: BebraBebra
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    generate-ddl: true
  cloud:
    aws:
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
        region: eu-central-1
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
      region:
        static: eu-central-1
      sqs:
        endpoint: http://localhost:4566
        queue-url: http://localhost:4566/000000000000/songfile-queue

storage:
  local:
    path: /storage
  s3:
    bucket-name: songfile

logging:
  level:
    root=INFO: