server:
  port: 0

#TODO change db url
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/innowise-microservices-song-api
    password: BebraBebra
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    generate-ddl: true
  cloud:
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    region:
      static: eu-central-1
    sqs:
      endpoint: http://localhost:4566

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka