server:
  port: 0

#TODO change db url
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/innowise-microservices-song-api
    password: BebraBebra
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka