version: '3.8'
services:
  config-service:
    container_name: config-service
    build: ./config-service
    image: config-service:latest
    restart: always
    ports:
      - '8888:8888'
  enricher-api:
    container_name: enricher-api
    build: ./enricher-api
    image: enricher-api:latest
    restart: always
    environment:
      - CONFIG_SERVICE
    depends_on:
      - config-service
      - eureka-discovery-service
      - localstack
  eureka-discovery-service:
    container_name: eureka-discovery-service
    build: ./eureka-discovery-service
    image: eureka-discovery-service:latest
    restart: always
    ports:
      - '8761:8761'
    environment:
      - CONFIG_SERVICE
    depends_on:
      - config-service
  file-api:
    build: ./file-api
    restart: always
    environment:
      - CONFIG_SERVICE
    depends_on:
      - mysql
      - config-service
      - eureka-discovery-service
      - localstack
  song-api:
    build: ./song-api
    image: song-api:latest
    restart: always
    environment:
      - CONFIG_SERVICE
    depends_on:
      - config-service
      - eureka-discovery-service
      - localstack
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=BebraBebra
      - MYSQL_DATABASE=innowise-microservices-file-api
    volumes:
      - /var/lib/mysql

  localstack:
    image: localstack/localstack:2.1.0
    restart: always
    ports:
      - '4563-4599:4563-4599'
      - '8055:8055'
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
#      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'