version: '3.8'
services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    image: api-gateway:latest
    restart: always
    environment:
      - CONFIG_SERVICE_URI=${CONFIG_SERVICE_URI}
      - EUREKA_DISCOVERY_URI=${EUREKA_DISCOVERY_URI}
    ports:
      - '8082:8082'
    depends_on:
      - config-service
      - eureka-discovery-service
      - song-api
      - enricher-api
      - file-api
  config-service:
    container_name: config-service
    build: ./config-service
    image: config-service:latest
    restart: always
    environment:
      - EUREKA_DISCOVERY_URI=${EUREKA_DISCOVERY_URI}
    ports:
      - '8888:8888'
  enricher-api:
    container_name: enricher-api
    build: ./enricher-api
    image: enricher-api:latest
    restart: always
    environment:
      - CONFIG_SERVICE_URI=${CONFIG_SERVICE_URI}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - EUREKA_DISCOVERY_URI=${EUREKA_DISCOVERY_URI}
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - config-service
      - eureka-discovery-service
      - localstack
  eureka-discovery-service:
    container_name: eureka-discovery-service
    build: ./eureka-discovery-service
    image: eureka-discovery-service:latest
    restart: always
    ports:
      - '8761:8761'
    environment:
      - CONFIG_SERVICE_URI=${CONFIG_SERVICE_URI}
    depends_on:
      - config-service
  file-api:
    build: ./file-api
    restart: always
    environment:
      - CONFIG_SERVICE_URI=${CONFIG_SERVICE_URI}
      - MYSQL_HOST=mysql-file-api
      - EUREKA_DISCOVERY_URI=${EUREKA_DISCOVERY_URI}
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - mysql-file-api
      - config-service
      - eureka-discovery-service
      - localstack
  song-api:
    build: ./song-api
    image: song-api:latest
    restart: always
    environment:
      - CONFIG_SERVICE_URI=${CONFIG_SERVICE_URI}
      - MYSQL_HOST=mysql-song-api
      - EUREKA_DISCOVERY_URI=${EUREKA_DISCOVERY_URI}
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - config-service
      - eureka-discovery-service
      - localstack
      - mysql-song-api
  mysql-file-api:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=BebraBebra
      - MYSQL_DATABASE=innowise-microservices-file-api
    volumes:
      - /var/lib/mysql-file-api
  mysql-song-api:
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=BebraBebra
      - MYSQL_DATABASE=innowise-microservices-song-api
    volumes:
      - /var/lib/mysql-song-api
  localstack:
    image: localstack/localstack:2.1.0
    restart: always
    ports:
      - '4563-4599:4563-4599'
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    volumes:
      - ./localstack-init-script:/etc/localstack/init/ready.d
      - '/var/run/docker.sock:/var/run/docker.sock'