version: "3.8"
services:
  file:
    build: ./file-api
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=BebraBebra
      - MYSQL_DATABASE=innowise-microservices-file-api
    volumes:
      - /var/lib/mysql

#  localstack:
#    image: localstack/localstack
#    ports:
#      - "4572:4572"
#    environment:
#      - SERVICES=s3
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    volumes:
#      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"