spring:
  datasource:
    url: jdbc:mysql://localhost:3306/innowise-microservices-file-api
    password: BebraBebra
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
storage:
  local:
    path: D:\Java\Innowise Tasks\task5-microservices\storage